dev:
  configs:
    "spark.hadoop.fs.azure.account.oauth2.client.endpoint" : "https://login.microsoftonline.com/5d93ebcc-f769-4380-8b7e-289fc972da1b/oauth2/token"
    "spark.hadoop.fs.azure.account.oauth.provider.type" : "org.apache.hadoop.fs.azurebfs.oauth2.ClientCredsTokenProvider"
    "spark.hadoop.fs.azure.account.oauth2.client.id" : "{{secrets/yadl-managed-dbr-scope/yadlSpEtlClientId}}"
    "spark.hadoop.javax.jdo.option.ConnectionDriverName" : "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    "spark.hadoop.fs.azure.account.oauth2.client.secret" : "{{secrets/yadl-managed-dbr-scope/yadlSpEtlSecretId}}"
    "spark.master" : "local[*, 4]"
    "spark.databricks.cluster.profile" : "singleNode"
  tags:
    component : kafka_from_dd
  policyId: C96178C1CF00011D
cer:
  configs:
    "spark.hadoop.fs.azure.account.oauth2.client.endpoint" : "https://login.microsoftonline.com/5d93ebcc-f769-4380-8b7e-289fc972da1b/oauth2/token"
  tags:
    component : kafka_from_dd
  policyId: XDDFF3334444
pro:
  configs:
    "spark.hadoop.fs.azure.account.oauth2.client.endpoint" : "https://login.microsoftonline.com/5d93ebcc-f769-4380-8b7e-289fc972da1b/oauth2/token"
  tags:
    component : kafka_from_dd
  policyId: XDDFF3334444
  